import Image from "next/image";

const SkillsLanguageInfinite = () => {
	return (
		<div
			className='scroller'
			//style={{ "--time": "20s" } as React.CSSProperties}
		>
			<div className='tag-list scroller__inner'>
				<span>
					<Image src='/skills/html.png' alt='Html' width={100} height={100} />
				</span>
				<span>
					<Image src='/skills/css.png' alt='Css' width={100} height={100} />
				</span>
				<span>
					<Image
						src='/skills/js.png'
						alt='JavaScript'
						width={100}
						height={100}
					/>
				</span>
				<span>
					<Image src='/skills/git.png' alt='Git' width={100} height={100} />
				</span>
				<span>
					<Image
						src='/skills/github.png'
						alt='GitHub'
						width={100}
						height={100}
					/>
				</span>
				<span>
					<Image
						src='/skills/tailwind.png'
						alt='Tailwind'
						width={100}
						height={100}
					/>
				</span>
				<span>
					<Image src='/skills/figma.png' alt='Figma' width={100} height={100} />
				</span>
				<span>
					<Image
						src='/skills/react.png'
						alt='ReactJS'
						width={100}
						height={100}
					/>
				</span>
				<span>
					<Image
						src='/skills/nextjs2.png'
						alt='NextJS2'
						width={100}
						height={100}
					/>
				</span>
				<span>
					<Image
						src='/skills/typescript.png'
						alt='Typescript'
						width={100}
						height={100}
					/>
				</span>
				<span>
					<Image
						src='/skills/zustand.png'
						alt='Zustand'
						width={100}
						height={100}
					/>
				</span>
				<span>
					<Image
						src='/skills/nodejs.png'
						alt='NodeJS'
						width={100}
						height={100}
					/>
				</span>
				<span>
					<Image
						src='/skills/sequelize.png'
						alt='Sequelize'
						width={100}
						height={100}
					/>
				</span>
				<span>
					<Image
						src='/skills/postgres.png'
						alt='Postgres'
						width={100}
						height={100}
					/>
				</span>{" "}
				<span>
					<Image src='/skills/html.png' alt='Html' width={100} height={100} />
				</span>
				<span>
					<Image src='/skills/css.png' alt='Css' width={100} height={100} />
				</span>
				<span>
					<Image
						src='/skills/js.png'
						alt='JavaScript'
						width={100}
						height={100}
					/>
				</span>
				<span>
					<Image src='/skills/git.png' alt='Git' width={100} height={100} />
				</span>
				<span>
					<Image
						src='/skills/github.png'
						alt='GitHub'
						width={100}
						height={100}
					/>
				</span>
				<span>
					<Image
						src='/skills/tailwind.png'
						alt='Tailwind'
						width={100}
						height={100}
					/>
				</span>
				<span>
					<Image src='/skills/figma.png' alt='Figma' width={100} height={100} />
				</span>
				<span>
					<Image
						src='/skills/react.png'
						alt='ReactJS'
						width={100}
						height={100}
					/>
				</span>
				<span>
					<Image
						src='/skills/nextjs2.png'
						alt='NextJS'
						width={100}
						height={100}
					/>
				</span>
				<span>
					<Image
						src='/skills/typescript.png'
						alt='Typescript'
						width={100}
						height={100}
					/>
				</span>
				<span>
					<Image
						src='/skills/zustand.png'
						alt='Zustand'
						width={100}
						height={100}
					/>
				</span>
				<span>
					<Image
						src='/skills/nodejs.png'
						alt='NodeJS'
						width={100}
						height={100}
					/>
				</span>
				<span>
					<Image
						src='/skills/sequelize.png'
						alt='Sequelize'
						width={100}
						height={100}
					/>
				</span>
				<span>
					<Image
						src='/skills/postgres.png'
						alt='Postgres'
						width={100}
						height={100}
					/>
				</span>
			</div>
		</div>
	);
};

export default SkillsLanguageInfinite;
